### ISSUE TITLE
link de trabalho da semana 1

### ISSUE THREAD

**Issue by cris-luz-07** [Desprograme/curso-hello.world#1]

**Comment by cris-luz-90-9** [comment]
https://github.com/cris-luz-90-9/helloword-ex

**Comment by yoneshinzato** [comment]
https://github.com/yoneshinzato/helloworld-ex/tree/master/exe_1_semana_1

**Comment by oliveira-ana** [comment]
https://github.com/Oliveira-Ana/helloworld-ex

**Comment by GuilhermeCoelhoAzevedo** [comment]
https://github.com/GuilhermeCoelhoAzevedo/helloword-ex

**Comment by tatianagcamara** [comment]
https://github.com/tatianagcamara/helloword-ex

**Comment by dssfernanda** [comment]
https://github.com/dssfernanda/helloword-ex

obs: texto errado :/

**Comment by michellisf** [comment]
https://github.com/michellisf/helloword-ex

**Comment by Noriene-Marques** [comment]
https://github.com/noriene/helloworld-ex.

**Comment by anaport** [comment]
https://github.com/anaport/helloword-ex

**Comment by PriscilaKis** [comment]
https://github.com/PriscilaKis/helloword-ex

**Comment by iamdivaloper** [comment]
https://github.com/eudivaloper/helloword-ex

**Comment by simonecabral** [comment]
https://github.com/simonecabral/helloword-ex.git

**Comment by Ivana46** [comment]
https://github.com/Ivana46/-helloword-ex

**Comment by carlacrude** [comment]
https://github.com/carlacrude/helloworld-ex

**Comment by PriscilaKis** [comment]
https://github.com/PriscilaKis/helloword-ex

**Comment by jehferrara** [comment]
https://github.com/jehferrara/helloword-ex-

**Comment by aledias48** [comment]
https://github.com/aledias48/exe-1

**Comment by ellengmelo** [comment]
https://github.com/Ellengmelo/helloword-ex

**Comment by aledias48** [comment]
https://github.com/aledias48/exe-1

**Comment by edvanias** [comment]
https://github.com/edvanias/-helloword-ex

**Comment by camilamlima** [comment]
https://github.com/camilamlima/helloword-ex

**Comment by andreiacbb** [comment]
https://github.com/andreiacbb/helloworld-ex

**Comment by fesanto** [comment]
https://github.com/FeSanto/helloword-ex

**Comment by marianamleandro** [comment]
https://github.com/marianamleandro/helloword-ex

**Comment by BrunaChris** [comment]
https://github.com/BrunaChris/helloword-ex

**Comment by mioliveira3** [comment]
https://github.com/mioliveira3/helloword-ex

**Comment by fesanto** [comment]
https://github.com/FeSanto/helloword-ex

**Comment by baliborio** [comment]
https://github.com/baliborio/helloword-ex

**Comment by paulabrumate2004** [comment]
https://github.com/paulabrumate2004/aula3 (segundo trabalho)

**Comment by MarSouza28** [comment]
https://github.com/MarSouza28/helloword-ex

**Comment by ellengmelo** [comment]
https://github.com/Ellengmelo/helloword-ex

**Comment by ingridmazoni01** [comment]
https://github.com/ingridmazoni01/helloword-ex/

**Comment by michellisf** [comment]
Exercício 2: https://github.com/michellisf/helloword-ex/tree/master/exe%202%20-%20semana%201

**Comment by edvanias** [comment]
https://github.com/edvanias/helloword-ex

**Comment by thaisnuness** [comment]
https://github.com/ThaisNunes01/helloword-ex

**Comment by aledias48** [comment]
https://github.com/aledias48/helloword-ex

**Comment by Ivana46** [comment]
https://github.com/Ivana46/helloword-ex/blob/master/exe2.html

**Comment by camilamlima** [comment]
Exe.2
https://github.com/camilamlima/helloword-ex/blob/master/exe%202.html

**Comment by cintia-barpe** [comment]
https://github.com/cintia-barpe/helloword-ex

**Comment by puinha** [comment]
https://github.com/puinha/helloword-ex

https://github.com/puinha/helloword-ex/tree/master/exe1

**Comment by anamenici** [comment]
https://github.com/anamenici/helloword-ex

**Comment by estersto** [comment]
https://github.com/estersto/helloworld-ex

**Comment by ahmatrai** [comment]
https://github.com/ahmatrai/helloword-ex

**Comment by gabrielacobra** [comment]
https://github.com/gabrielacobra/helloword-ex

**Comment by gabrielacobra** [comment]
https://github.com/gabrielacobra/helloword-ex

**Comment by ghost** [comment]
https://github.com/ReginaFreitas2017/helloworld-ex
https://github.com/ReginaFreitas2017/helloworld-ex/blob/master/ex1-semana1.html

**Comment by Gabrielatcwt** [comment]
https://github.com/Icouldbekilling/helloword-ex

**Comment by naiagp** [comment]
https://github.com/naiagp/helloword-ex

**Comment by mocraveirodev** [comment]
https://github.com/monikinhanx/helloworld-ex/blob/master/ex1.html

**Comment by cris-luz-07** [comment]
"Edição curso -1 - Closed"

**Comment by dssfernanda** [comment]
https://github.com/dssfernanda/helloword-ex/tree/master/Exerc%C3%ADcios

**Comment by dssfernanda** [comment]
https://github.com/dssfernanda/helloword-ex/tree/master/Ex1_site

**Comment by dssfernanda** [comment]
https://github.com/dssfernanda/helloword-ex/tree/master/Javascript_Exerc%C3%ADcios__parte%201

**Comment by bianavic** [comment]
https://github.com/bianavic/helloword-ex/commit/d87f6c96016bc9a5c6471e1be90d731bd5685376
