### ISSUE TITLE
Semana 3 #Bootstrap  [ Atividades]

### ISSUE THREAD

**Issue by cris-luz-07** [Desprograme/curso-hello.world#15]

**Comment by thaisnuness** [comment]
https://github.com/ThaisNunes01/helloword-ex/tree/master/site

**Comment by carlacrude** [comment]
https://github.com/carlacrude/helloworld-ex/tree/master/exe%2010%20(Booststrap)

**Comment by camilamlima** [comment]
https://github.com/camilamlima/helloword-ex/tree/master/ex_site_semana_3_ex_1

**Comment by baliborio** [comment]
https://github.com/baliborio/helloword-ex/tree/master/Bootstrap%20-%20exe

**Comment by GuilhermeCoelhoAzevedo** [comment]
https://github.com/GuilhermeCoelhoAzevedo/helloworld-ex/tree/master/Exercicio%2010

**Comment by dssfernanda** [comment]
https://github.com/dssfernanda/helloword-ex/tree/master/Bootstrap%20pt%201%20e%202__Exerc%C3%ADcios

**Comment by naiagp** [comment]
https://github.com/naiagp/Semana-3-Bootstrap

**Comment by fesanto** [comment]
https://github.com/FeSanto/helloword-ex

**Comment by pamelasouza** [comment]
https://github.com/pamelasouza/desprograme/tree/master/exercicio%209

**Comment by jfranquis** [comment]
[https://github.com/Desprograme/curso-hello.world/issues/15](url)

**Comment by mocraveirodev** [comment]
https://github.com/monikinhanx/helloworld-ex/tree/master/site

**Comment by simonecabral** [comment]
https://github.com/simonecabral/helloword-ex.git/index.html
https://github.com/simonecabral/helloword-ex.git/ada.html
https://github.com/simonecabral/helloword-ex.git/grace.html
https://github.com/simonecabral/helloword-ex.git/hedy.html
https://github.com/simonecabral/helloword-ex.git/irma.html
https://github.com/simonecabral/helloword-ex.git/carol.html
https://github.com/simonecabral/helloword-ex.git/radia.html
https://github.com/simonecabral/helloword-ex.git/style.css

**Comment by erikamassafera** [comment]
https://github.com/erikamassafera/desprograme/blob/master/ada.html
https://github.com/erikamassafera/desprograme/blob/master/carol.html
https://github.com/erikamassafera/desprograme/blob/master/grace.html
https://github.com/erikamassafera/desprograme/blob/master/hedy.html
https://github.com/erikamassafera/desprograme/blob/master/irma.html
https://github.com/erikamassafera/desprograme/blob/master/radia.html

**Comment by mioliveira3** [comment]
https://github.com/mioliveira3/helloword-ex/tree/master/bootstrap

**Comment by cris-luz-07** [comment]
"Edição curso -1 - Closed"
