### ISSUE TITLE
Link do trabalho da semana 1

### ISSUE THREAD

**Issue by moniquesoares86** [Desprograme/curso-hello.world#2]

**Comment by moniquesoares86** [comment]
https://github.com/moniquesoares86/helloword-ex

**Comment by baliborio** [comment]
https://github.com/baliborio/helloword-ex

**Comment by thaisnuness** [comment]
https://github.com/ThaisNunes01/helloword-ex

**Comment by BrunaChris** [comment]
https://github.com/BrunaChris/helloword-ex

**Comment by paulabrumate2004** [comment]
https://github.com/paulabrumate2004/helloword-ex

**Comment by baliborio** [comment]
https://github.com/baliborio/helloword-ex
https://github.com/baliborio/helloword-ex/tree/master/exe%202

(segundo trabalho)

**Comment by carlacrude** [comment]
https://github.com/carlacrude/helloworld-ex

**Comment by oliveira-ana** [comment]
https://github.com/Oliveira-Ana/helloworld-ex

**Comment by Noriene-Marques** [comment]
https://github.com/noriene/helloworld-ex2

**Comment by GuilhermeCoelhoAzevedo** [comment]
https://github.com/GuilhermeCoelhoAzevedo/helloworld-ex

**Comment by tatianagcamara** [comment]
https://github.com/tatianagcamara/helloword-ex
https://github.com/tatianagcamara/helloword-ex/blob/master/exe2.html

**Comment by puinha** [comment]
https://github.com/puinha/helloword-ex
https://github.com/puinha/helloword-ex/tree/master/exe2

**Comment by ghost** [comment]
https://github.com/ReginaFreitas2017/helloworld-ex
https://github.com/ReginaFreitas2017/helloworld-ex/blob/master/exe2-semana1.html

**Comment by mocraveirodev** [comment]
https://github.com/monikinhanx/helloworld-ex/blob/master/ex1.html

**Comment by cris-luz-07** [comment]
"Edição curso -1 - Closed"
