### ISSUE TITLE
[ Curso Hello World turma 2 ] - Coloque o link do seu repositório do Github

### ISSUE THREAD

**Issue by cris-luz-07** [Desprograme/curso-hello.world#20]
[ Curso Hello World turma 2 ] - Coloque o link do seu repositório do Github

**Comment by thaisjsoares** [comment]
https://github.com/tjacoe/hello-world

**Comment by LeilaFerreira** [comment]
https://github.com/LeilaFerreira/hello-world

**Comment by airenata** [comment]
https://github.com/airenata/hello-world

**Comment by librarysciences** [comment]
https://github.com/librarysciences/hello-world

**Comment by DebsCamacho** [comment]
https://github.com/DebsCamacho/hello-world

**Comment by elviraafmiranda** [comment]
https://github.com/elviraafmiranda/hello-world

**Comment by cabdo** [comment]
https://github.com/cabdo/hello-world

**Comment by cpnborges** [comment]
https://github.com/cpnborges/hello-world

**Comment by julianasm91** [comment]
https://github.com/julianasm91/helloword-exe/blob/master/ex1.html

**Comment by julianasm91** [comment]
https://github.com/julianasm91/helloword-exe

**Comment by emtakata** [comment]
https://github.com/emtakata/helloworld-ex

**Comment by Sandriela** [comment]
file:///C:/Users/adm/Desktop/ex1.html/html.html

**Comment by Sandriela** [comment]
file:///C:/Users/adm/Desktop/ex1.html/html.html @Sandriela  não consigo ter acesso as suas atividades

**Comment by msfabi3** [comment]
https://github.com/msfabi3/hello-world

**Comment by msfabi3** [comment]
https://github.com/msfabi3/helloworld

**Comment by nadirayanez** [comment]
https://github.com/nadirayanez/helloword-ex

**Comment by bialeca** [comment]
https://github.com/bialeca/EXE-1/

**Comment by bialeca** [comment]
https://github.com/bialeca/exe1

**Comment by msfabi3** [comment]
https://github.com/msfabi3/helloworld

Em ter, 10 de jul de 2018 00:56, bialeca <notifications@github.com>
escreveu:

**Comment by anapcanha** [comment]
https://github.com/anapcanha/helloword

**Comment by isafloriano** [comment]
https://github.com/isafloriano/hello-world

**Comment by cristianefmartins** [comment]
https://github.com/cristianefmartins/curso-hello.world

**Comment by eiscruz** [comment]
https://github.com/eiscruz/hello-world.git  @eiscruz  não conseguir visualizar as atividades, me chama no Whats :)

**Comment by cintiamartins7** [comment]
https://github.com/cintiamartins7/hello-world

**Comment by annarossi** [comment]
https://github.com/annarossi/hello-world

**Comment by marciacostaz** [comment]
https://github.com/MarciaCosan/helloword-exe

**Comment by bianavic** [comment]
https://github.com/bianavic/helloword-ex

**Comment by fortini** [comment]
https://github.com/fortini/helloworld-ex

**Comment by feteruya** [comment]
https://github.com/feteruya/helloword-ex/tree/master/ex_semana2

**Comment by renatatonelotti** [comment]
https://github.com/renatatonelotti/hellowword-ex

**Comment by renatatonelotti** [comment]
https://github.com/renatatonelotti/hellowword-ex

**Comment by julianasm91** [comment]
https://github.com/julianasm91/helloword-exe

**Comment by dnijlima** [comment]
https://github.com/dnijlima/helloworld-ex

**Comment by shirleyags** [comment]
https://github.com/shirleyags/helloword-ex

**Comment by nicolefmorely** [comment]
https://github.com/nicolefmorely/helloword-ex

**Comment by marciacostaz** [comment]
https://github.com/MarciaCosan/ex1_part3

Em Ter, 17 de jul de 2018 00:04, Nicole Morely <notifications@github.com>
escreveu:

**Comment by isadoraperes** [comment]
https://github.com/isadoraperes/helloworld-ex

**Comment by isadoraperes** [comment]
https://github.com/isadoraperes/helloworld-ex/tree/master/ex_1 

Versão "final", com todos os exercícios resolvidos.

**Comment by ghost** [comment]
https://github.com/gisapedroli/helloworld-ex/blob/master/README.md

**Comment by AriDaurea** [comment]
https://github.com/AriDaurea/helloword-ex

**Comment by Franbitten** [comment]
https://github.com/Franbitten/helloword-ex

**Comment by patyy** [comment]
https://github.com/Desprograme/curso-hello.world/issues/24

**Comment by patyy** [comment]
https://github.com/patyy/h

**Comment by MarSouza28** [comment]
https://github.com/MarSouza28/-helloword-ex

**Comment by Andreia-Marques** [comment]
https://github.com/Andreia-Marques/helloword-ex

**Comment by Andreia-Marques** [comment]
https://github.com/Andreia-Marques/helloword-exComplete

**Comment by cris-luz-07** [comment]
finalizada seleção :)
