### ISSUE TITLE
Link do trabalho da semana 1.

### ISSUE THREAD

**Issue by StrelitziaLicht92** [Desprograme/curso-hello.world#3]
https://github.com/StrelitziaLicht92/helloword-ex/blob/master/exe1.html

**Comment by dssfernanda** [comment]
https://github.com/dssfernanda/helloword-ex/blob/master/ex2.html

**Comment by puinha** [comment]
https://github.com/puinha/helloword-ex
https://github.com/puinha/helloword-ex/tree/master/exe3

**Comment by mocraveirodev** [comment]
https://github.com/monikinhanx/helloworld-ex/blob/master/ex1.html

**Comment by cris-luz-07** [comment]
"Edição curso -1 - Closed"
