### ISSUE TITLE
Semana 1 [ Site das Mulheres na Tecnologia ]

### ISSUE THREAD

**Issue by cris-luz-07** [Desprograme/curso-hello.world#8]
Você deverá posta o link do seu trabalho final da Aula de <html>

**Comment by fesanto** [comment]
https://github.com/FeSanto/helloword-ex

**Comment by michellisf** [comment]
https://github.com/michellisf/helloword-ex/tree/master/site_semana1

Ficou bom, essa semana será css. 

Parabéns

**Comment by talitarc** [comment]
https://github.com/talitarc/helloworld-ex

**Comment by anamenici** [comment]
https://github.com/anamenici/helloword-ex

**Comment by estersto** [comment]
https://github.com/estersto/helloworld-ex/tree/master/site_semana%201

**Comment by carlacrude** [comment]
https://github.com/carlacrude/helloworld-ex/tree/master/exe%204

**Comment by tatianagcamara** [comment]
https://github.com/tatianagcamara/helloword-ex

**Comment by GuilhermeCoelhoAzevedo** [comment]
https://github.com/GuilhermeCoelhoAzevedo/helloworld-ex/tree/master/Site%20semana%201

**Comment by baliborio** [comment]
https://github.com/baliborio/helloword-ex/tree/master/exe%204

**Comment by paulabrumate2004** [comment]
https://github.com/paulabrumate2004/site-mulheres-

**Comment by Noriene-Marques** [comment]
https://github.com/noriene/helloworld-ex4

**Comment by dssfernanda** [comment]
https://github.com/dssfernanda/helloword-ex/blob/master/carol.html

https://github.com/dssfernanda/helloword-ex/blob/master/grace.html

https://github.com/dssfernanda/helloword-ex/blob/master/hedy.html

https://github.com/dssfernanda/helloword-ex/blob/master/irma.html

https://github.com/dssfernanda/helloword-ex/blob/master/radia.html

https://github.com/dssfernanda/helloword-ex/blob/master/Index.html

**Comment by yoneshinzato** [comment]
https://github.com/yoneshinzato/helloworld-ex/tree/master/exe_4_semana_1

**Comment by camilamlima** [comment]
https://github.com/camilamlima/helloword-ex/tree/master/ex_site

**Comment by thaisnuness** [comment]
https://github.com/ThaisNunes01/helloword-ex/tree/master/exe%204

**Comment by thaisnuness** [comment]
CSS
https://github.com/ThaisNunes01/helloword-ex/tree/master/exe5

**Comment by gabrielacobra** [comment]
https://github.com/gabrielacobra/helloword-ex/tree/master/exe4

**Comment by mioliveira3** [comment]
https://github.com/mioliveira3/helloword-ex/tree/master/exe4

**Comment by ghost** [comment]
https://github.com/ReginaFreitas2017/helloworld-ex/blob/master/site-mulheres-programacao.rar

**Comment by reginafreitas** [comment]
https://github.com/reginafreitas/helloworld-ex/blob/master/site-mulheres-programacao.rar

**Comment by oliveira-ana** [comment]
https://github.com/Oliveira-Ana/helloworld-ex

**Comment by ahmatrai** [comment]
https://github.com/ahmatrai/helloworld-ex/blob/master/index.html
https://github.com/ahmatrai/helloworld-ex/blob/master/ada.html
https://github.com/ahmatrai/helloworld-ex/blob/master/grace.html
https://github.com/ahmatrai/helloworld-ex/blob/master/hedy.html
https://github.com/ahmatrai/helloworld-ex/blob/master/irma.html
https://github.com/ahmatrai/helloworld-ex/blob/master/carol.html
https://github.com/ahmatrai/helloworld-ex/blob/master/radia.html
https://github.com/ahmatrai/helloworld-ex

**Comment by naiagp** [comment]
https://github.com/naiagp/Site

**Comment by mocraveirodev** [comment]
https://github.com/monikinhanx/helloworld-ex/tree/master/site

**Comment by simonecabral** [comment]
https://github.com/simonecabral/helloword-ex.git/index.html
https://github.com/simonecabral/helloword-ex.git/grace.html
https://github.com/simonecabral/helloword-ex.git/ada.html
https://github.com/simonecabral/helloword-ex.git/hedy.html
https://github.com/simonecabral/helloword-ex.git/irma.html
https://github.com/simonecabral/helloword-ex.git/carol.html
https://github.com/simonecabral/helloword-ex.git/radia.html

**Comment by puinha** [comment]
https://github.com/puinha/helloword-ex/tree/master/exe-site

**Comment by cris-luz-07** [comment]
"Edição curso -1 - Closed"

**Comment by airenata** [comment]
https://github.com/airenata/hello_world_ex/tree/master/exe_3

**Comment by bianavic** [comment]
https://github.com/bianavic/helloword-ex/commit/97a2fc7005c9f85e5748ca0c3097ca55a14b2d66

**Comment by julianasm91** [comment]
https://github.com/julianasm91/helloword-exe/blob/master/hedy.html
https://github.com/julianasm91/helloword-exe/blob/master/irma.html
https://github.com/julianasm91/helloword-exe/blob/master/carol.html
https://github.com/julianasm91/helloword-exe/blob/master/radia.html
https://github.com/julianasm91/helloword-exe/blob/master/ada.html

**Comment by feteruya** [comment]
https://github.com/feteruya/helloword-ex/tree/master/ex1/ex4_semana1

**Comment by renatatonelotti** [comment]
https://github.com/renatatonelotti/hellowword-ex/tree/master/exe%204

**Comment by marciacostaz** [comment]
https://github.com/MarciaCosan/ex1_part4

**Comment by shirleyags** [comment]
https://github.com/shirleyags/helloword-ex-site

**Comment by ghost** [comment]
[index.zip](https://github.com/Desprograme/curso-hello.world/files/2247336/index.zip)
[irma.zip](https://github.com/Desprograme/curso-hello.world/files/2247337/irma.zip)
[carol.zip](https://github.com/Desprograme/curso-hello.world/files/2247338/carol.zip)
[hedy.zip](https://github.com/Desprograme/curso-hello.world/files/2247339/hedy.zip)
[ada.zip](https://github.com/Desprograme/curso-hello.world/files/2247340/ada.zip)
[radia.zip](https://github.com/Desprograme/curso-hello.world/files/2247341/radia.zip)
[grace.zip](https://github.com/Desprograme/curso-hello.world/files/2247342/grace.zip)

**Comment by Franbitten** [comment]
https://github.com/Franbitten/helloword-ex
